export interface Post {
  id: string;
  subject: string;
  tag: string;
  title: string;
  description: string | null;
  author: string;
  role: string;
  time: string;
  votes: number;
  comments: number;
  imageUrl: string | null;
}

export const MOCK_DATA: Post[] = [
  {
    id: "1",
    subject: "d://conquistas",
    tag: "#vida",
    title:
      "Finalmente consegui meu primeiro emprego na gringa e não tenho ninguém pra contar",
    description:
      "Depois de 2 anos estudando igual um maluco e tomando 40 nãos, a oferta veio. O salário é em dólar e eu ainda não processei que minha vida vai mudar.",
    author: "User99",
    role: "OP",
    time: "2 h",
    votes: 1240,
    comments: 156,
    imageUrl: null,
  },
  {
    id: "2",
    subject: "d://vagasArrombadas",
    tag: "#carreira",
    title: "A bolha estourou ou o sarrafo que subiu demais?",
    description:
      "Vagas de Junior pedindo 3 anos de experiência e conhecimento em Kubernetes. Tá difícil pra todo mundo ou eu que tô obsoleto?",
    author: "DevSenior",
    role: "Moderador",
    time: "5 h",
    votes: 450,
    comments: 89,
    imageUrl: null,
  },
  {
    id: "3",
    subject: "d://farialimabets",
    tag: "#loss",
    title: "Perdi 15k em opções e minha esposa não sabe",
    description:
      "Achei que ia dar o 'pulo do gato' esse mês. Como contar que a viagem de férias agora é pro quintal de casa?",
    author: "FariaLimer",
    role: "Membro",
    time: "45 min",
    votes: 890,
    comments: 210,
    imageUrl:
      "https://i.pinimg.com/736x/ab/35/87/ab3587228e445ebbaaea729364a73ccc.jpg",
  },
  {
    id: "4",
    subject: "d://gaming",
    tag: "#hype",
    title: "O novo trailer de GTA VI quebrou a internet de novo",
    description: null,
    author: "GamerPro",
    role: "Viciado",
    time: "10 min",
    votes: 5600,
    comments: 432,
    imageUrl:
      "https://i.pinimg.com/736x/48/70/1c/48701c946114e2240e976377c8ddcd51.jpg",
  },
  {
    id: "5",
    subject: "d://futebol",
    tag: "#meme",
    title: "POV: Você torce pro time que tá na lanterna",
    description:
      "Todo domingo é uma depressão diferente. Até quando, meu Deus?",
    author: "Sofredor_FC",
    role: "Zoeiro",
    time: "3 h",
    votes: 320,
    comments: 45,
    imageUrl: null,
  },
  {
    id: "6",
    subject: "d://tecnologia",
    tag: "#notícia",
    title: "Nova IA do Google consegue simular universos inteiros?",
    description:
      "O artigo publicado hoje sugere que a capacidade de processamento atingiu um nível que beira a ficção científica.",
    author: "TechNews",
    role: "Jornalista",
    time: "1 d",
    votes: 2100,
    comments: 300,
    imageUrl:
      "https://i.pinimg.com/736x/42/52/60/425260cab211aba8cc813c994e8ff172.jpg",
  },
  {
    id: "7",
    subject: "d://pergunteAoReddit",
    tag: "#curiosidade",
    title:
      "Qual foi a coisa mais estranha que você já viu no transporte público?",
    description:
      "Hoje vi um cara levando um pavão no metrô de SP. Nada mais me surpreende.",
    author: "Curioso_123",
    role: "Viajante",
    time: "6 h",
    votes: 150,
    comments: 280,
    imageUrl: null,
  },
  {
    id: "8",
    subject: "d://meuSetup",
    tag: "#showcase",
    title: "Minimalismo no limite: Meu cantinho de 2026",
    description:
      "Tentei esconder todos os cabos. O que acharam desse efeito glitch no monitor?",
    author: "SetupMaster",
    role: "Designer",
    time: "12 h",
    votes: 980,
    comments: 67,
    imageUrl:
      "https://i.pinimg.com/1200x/a0/34/ab/a034abcdfa182b31382b8d69b7e26dd2.jpg",
  },
  {
    id: "9",
    subject: "d://gastronomia",
    tag: "#ajuda",
    title: "Como não queimar o arroz pela quinta vez seguida?",
    description:
      "Sigo a receita, mas o fundo sempre vira carvão. Aceito dicas de avó.",
    author: "Chef_Desastre",
    role: "Iniciante",
    time: "20 min",
    votes: 45,
    comments: 92,
    imageUrl: null,
  },
  {
    id: "10",
    subject: "d://cinema",
    tag: "#discussão",
    title: "Aquele final de Interstellar ainda me faz chorar igual uma criança",
    description:
      "Assisti pela décima vez ontem. A trilha sonora do Hans Zimmer é sacanagem.",
    author: "Cinefilo_Raiz",
    role: "Crítico",
    time: "8 h",
    votes: 750,
    comments: 110,
    imageUrl: null,
  },
  {
    id: "11",
    subject: "d://politicaBR",
    tag: "#debate",
    title: "Alguém realmente entendeu o novo imposto sobre memes?",
    description:
      "Vi a notícia mas parece piada de 1º de abril atrasada. Como vão taxar um JPEG?",
    author: "Cidadao_Puto",
    role: "Ativista",
    time: "14 h",
    votes: 1300,
    comments: 540,
    imageUrl: null,
  },
  {
    id: "12",
    subject: "d://pcmasterrace",
    tag: "#review",
    title:
      "RTX 6090 Ti: Precisei vender meu rim e puxar um disjuntor só pra ela",
    description:
      "O consumo de energia é maior que o da minha geladeira, mas o Ray Tracing em 16k é absurdo.",
    author: "Hardcore_PC",
    role: "Entusiasta",
    time: "2 d",
    votes: 340,
    comments: 120,
    imageUrl:
      "https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "13",
    subject: "d://musica",
    tag: "#playlist",
    title:
      "Músicas para codar às 3 da manhã sentindo que o café não faz mais efeito",
    description:
      "Muito Synthwave, Lo-fi e um pouco de Metal pra não dormir em cima do teclado.",
    author: "CodeBeats",
    role: "DJ do Terminal",
    time: "30 min",
    votes: 210,
    comments: 34,
    imageUrl: null,
  },
  {
    id: "14",
    subject: "d://viagem",
    tag: "#dicas",
    title: "Fui pro Japão sem saber falar 'oi' e sobrevivi",
    description:
      "O Google Translate salvou minha vida, mas quase comi carne de baleia achando que era bife.",
    author: "Mochileiro",
    role: "Explorador",
    time: "18 h",
    votes: 670,
    comments: 88,
    imageUrl:
      "https://i.pinimg.com/736x/4d/79/14/4d7914129bc7bd093b0c443996c10655.jpg",
  },
  {
    id: "15",
    subject: "d://astronomia",
    tag: "#astronomia",
    title: "Webb detecta sinal de rádio repetitivo vindo de Proxima B",
    description:
      "Pode ser só uma estrela de nêutrons, mas o padrão é matemático demais para ser natural.",
    author: "SpaceNerd",
    role: "Astrofísico",
    time: "4 h",
    votes: 4500,
    comments: 670,
    imageUrl: null,
  },
  {
    id: "16",
    subject: "d://maromba",
    tag: "#evolução",
    title: "6 meses de academia: Saí do shape de grilo para shape de calango",
    description:
      "Não é muito, mas o braço finalmente parou de balançar com o vento.",
    author: "FrangoEmBusca",
    role: "Maromba Jr",
    time: "1 d",
    votes: 540,
    comments: 130,
    imageUrl: null,
  },
  {
    id: "17",
    subject: "d://internetMorta",
    tag: "#teoria",
    title: "E se a internet na verdade acabou em 2016 e agora só tem bots?",
    description:
      "A Teoria da Internet Morta faz cada vez mais sentido quando vejo as trends do Twitter.",
    author: "X_File",
    role: "Acordado",
    time: "22 h",
    votes: 820,
    comments: 190,
    imageUrl: null,
  },
  {
    id: "18",
    subject: "d://carros",
    tag: "#antigos",
    title: "Achei um Opala 74 abandonado no celeiro do meu avô",
    description:
      "O motor tá travado e tem mais ferrugem que ferro, mas o projeto vai sair!",
    author: "PetrolHead",
    role: "Mecânico",
    time: "9 h",
    votes: 1100,
    comments: 150,
    imageUrl:
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "19",
    subject: "d://gatos",
    tag: "#fofura",
    title:
      "Meu gato aprendeu a abrir a geladeira e agora preciso de um cadeado",
    description:
      "Ele não quer comida, ele só quer sentar em cima das verduras geladas.",
    author: "CatLover",
    role: "Refém de Gato",
    time: "2 h",
    votes: 3200,
    comments: 95,
    imageUrl: null,
  },
  {
    id: "20",
    subject: "d://livros",
    tag: "#recomendações",
    title: "Terminei '1984' e agora estou com medo de olhar pro meu celular",
    description:
      "George Orwell não escreveu um livro, escreveu um manual de instruções.",
    author: "BookWorm",
    role: "Leitor",
    time: "5 h",
    votes: 600,
    comments: 140,
    imageUrl: null,
  },
  {
    id: "21",
    subject: "d://dev_pt",
    tag: "#horror",
    title: "Peguei um legado em COBOL pra dar manutenção hoje",
    description:
      "O código tem comentários datados de 1982. O autor provavelmente já reencarnou.",
    author: "DebugHell",
    role: "Escravo de Software",
    time: "7 h",
    votes: 430,
    comments: 76,
    imageUrl: null,
  },
  {
    id: "22",
    subject: "d://sobrenatural",
    tag: "#relato",
    title: "Tive uma paralisia do sono e o 'homem do chapéu' pediu meu Wi-Fi",
    description:
      "Foi bizarro, mas pelo menos ele não tentou me matar desta vez.",
    author: "Dreamer",
    role: "Místico",
    time: "11 h",
    votes: 215,
    comments: 112,
    imageUrl: null,
  },
  {
    id: "23",
    subject: "d://economia",
    tag: "#alerta",
    title: "O preço do azeite subiu tanto que agora estou usando como perfume",
    description: "R$ 50,00 o vidro? É melhor cozinhar com água benta.",
    author: "Pobre_Logica",
    role: "Economista",
    time: "3 d",
    votes: 1800,
    comments: 320,
    imageUrl: null,
  },
  {
    id: "24",
    subject: "d://midjourney",
    tag: "#arte",
    title: "Gerei como seria o Brasil se tivesse sido colonizado por Vikings",
    description:
      "O resultado ficou épico. Rio de Janeiro com neve e barcos dragão na baía.",
    author: "PromptWizard",
    role: "AI Artist",
    time: "4 h",
    votes: 1400,
    comments: 200,
    imageUrl:
      "https://i.pinimg.com/736x/fb/5b/a3/fb5ba3cfdbfe78b00d939507cefa0dac.jpg",
  },
  {
    id: "25",
    subject: "d://relacionamentos",
    tag: "#ajuda",
    title: "Minha namorada quer terminar porque eu não gosto de Shrek",
    description:
      "Ela diz que é uma falha de caráter imperdoável. Ela tá certa?",
    author: "ShrekHater",
    role: "Solteiro em breve",
    time: "1 h",
    votes: 900,
    comments: 1200,
    imageUrl: null,
  },
  {
    id: "26",
    subject: "d://animes",
    tag: "#news",
    title: "Hunter x Hunter voltará a ter capítulos semanais (sem pular!)",
    description: "Dessa vez o Togashi prometeu. Eu acredito, e vocês?",
    author: "OtakuHope",
    role: "Iludido",
    time: "30 min",
    votes: 5000,
    comments: 890,
    imageUrl: null,
  },
  {
    id: "27",
    subject: "d://marketing",
    tag: "#analise",
    title: "Por que as marcas estão postando shitpost agora?",
    description:
      "O estagiário da Netflix e do Burger King precisam ser estudados pela NASA.",
    author: "AdGuy",
    role: "Marketer",
    time: "15 h",
    votes: 310,
    comments: 45,
    imageUrl: null,
  },
  {
    id: "28",
    subject: "d://hojeEuAprendi",
    tag: "#curiosidade",
    title: "A guerra mais curta da história durou apenas 38 minutos",
    description: "Guerra Anglo-Zanzibariana. O tempo de um episódio de série.",
    author: "HistoryBuff",
    role: "Professor",
    time: "1 d",
    votes: 890,
    comments: 56,
    imageUrl: null,
  },
  {
    id: "29",
    subject: "d://sustentabilidade",
    tag: "#ideia",
    title: "E se transformássemos desertos em fazendas solares gigantes?",
    description:
      "O problema não é a energia, é o custo de levar ela até as cidades.",
    author: "GreenMind",
    role: "Engenheiro",
    time: "10 h",
    votes: 720,
    comments: 140,
    imageUrl:
      "https://i.pinimg.com/control1/736x/be/e5/75/bee575e744df3ebd2ddce1b3ad2da87b.jpg",
  },
  {
    id: "30",
    subject: "d://silksong",
    tag: "#indie",
    title: "Hollow Knight Silksong finalmente recebeu uma data?",
    description:
      "Não. Só queria ver vocês clicando rápido no post mesmo. Sofram comigo.",
    author: "ClownFace",
    role: "Palhaço",
    time: "5 min",
    votes: -150,
    comments: 400,
    imageUrl: null,
  },
];

export const MOCK_FOLLOWING: Post[] = [
  {
    id: "f1",
    subject: "d://dev_pt",
    tag: "#duvida",
    title: "Alguém aqui já migrou de Spring Boot para Go no backend?",
    description:
      "Tô sentindo que a JVM tá pesando demais pro meu microserviço atual. Vale o esforço da reescrita?",
    author: "Luiz Artur",
    role: "Dev Backend",
    time: "12 min",
    votes: 45,
    comments: 12,
    imageUrl: null,
  },
  {
    id: "f2",
    subject: "d://cybersec",
    tag: "#pwn",
    title: "Nova vulnerabilidade zero-day em roteadores domésticos",
    description:
      "O pessoal da segurança descobriu um bypass simples no firmware. Chequem os patches!",
    author: "Pedin",
    role: "Security Analyst",
    time: "1 h",
    votes: 320,
    comments: 24,
    imageUrl:
      "https://i.pinimg.com/736x/3f/0c/75/3f0c757fdd50707790cd70342d3fcd16.jpg",
  },
  {
    id: "f3",
    subject: "d://meuSetup",
    tag: "#upgrade",
    title: "Finalmente chegou o teclado mecânico custom!",
    description:
      "Switches lineares e keycaps de perfil baixo. O som é satisfatório demais.",
    author: "Paulo",
    role: "Hardware Enthusiast",
    time: "3 h",
    votes: 89,
    comments: 15,
    imageUrl:
      "https://i.pinimg.com/1200x/a0/c5/a8/a0c5a8fefb0aa77710b6361cebc72dc7.jpg",
  },
  {
    id: "f4",
    subject: "d://vagasArrombadas",
    tag: "#absurdo",
    title: "Exigiram teste técnico de 1 semana para vaga de estágio",
    description:
      "Pediram um clone do Uber com documentação completa e testes unitários. É rir pra não chorar.",
    author: "Dev_Cansado",
    role: "User",
    time: "5 h",
    votes: 1100,
    comments: 89,
    imageUrl: null,
  },
  {
    id: "f5",
    subject: "d://ia",
    tag: "#tutorial",
    title: "Como rodar o Llama 3 localmente com apenas 8GB de RAM",
    description:
      "Usei quantização em 4 bits e o desempenho ficou surpreendente.",
    author: "IA_Master",
    role: "Expert",
    time: "8 h",
    votes: 450,
    comments: 32,
    imageUrl: null,
  },
  {
    id: "f6",
    subject: "d://gaming",
    tag: "#review",
    title: "Elden Ring: Shadow of the Erdtree é o melhor DLC já feito?",
    description:
      "A dificuldade está insana, mas o level design é uma obra de arte.",
    author: "SoulsBorn",
    role: "Gamer",
    time: "10 h",
    votes: 2100,
    comments: 540,
    imageUrl:
      "https://i.pinimg.com/736x/9e/f5/83/9ef583deb5068a3d17500f7e7009d3ac.jpg",
  },
  {
    id: "f7",
    subject: "d://desabafos",
    tag: "#carreira",
    title: "O burnout chegou e eu não vi a cor dele",
    description:
      "Cuidado com o excesso de café e noites em claro. Nenhuma entrega vale sua saúde mental.",
    author: "Senior_Exausto",
    role: "Tech Lead",
    time: "14 h",
    votes: 980,
    comments: 120,
    imageUrl: null,
  },
  {
    id: "f8",
    subject: "d://farialimabets",
    tag: "#loss",
    title: "Apostei o aluguel no jogo do bicho e o bicho fugiu",
    description:
      "Dicas de como morar embaixo da ponte com estilo e Wi-Fi público?",
    author: "Apostador_Azarado",
    role: "Membro VIP",
    time: "1 d",
    votes: 2500,
    comments: 430,
    imageUrl: null,
  },
  {
    id: "f9",
    subject: "d://hojeEuAprendi",
    tag: "#curiosidade",
    title: "HEA que o primeiro bug de computador foi uma mariposa real",
    description:
      "Literalmente tiraram um inseto de dentro do computador em 1947.",
    author: "Historian_Tech",
    role: "Professor",
    time: "1 d",
    votes: 670,
    comments: 45,
    imageUrl: null,
  },
  {
    id: "f10",
    subject: "d://animes",
    tag: "#recompensa",
    title: "Solo Leveling: O final da temporada foi fiel ao Manhwa?",
    description:
      "A animação estava incrível, mas sinto que cortaram alguns diálogos importantes.",
    author: "Hunter_S",
    role: "Otaku",
    time: "2 d",
    votes: 1300,
    comments: 210,
    imageUrl: null,
  },
  {
    id: "f11",
    subject: "d://programacao",
    tag: "#humor",
    title: "Eu tentando ler o código que escrevi bêbado na sexta-feira",
    description: null,
    author: "Weekend_Coder",
    role: "Zoeiro",
    time: "2 d",
    votes: 890,
    comments: 56,
    imageUrl:
      "https://i.pinimg.com/736x/75/74/55/757455ced0849d33d130d1df659d7bac.jpg",
  },
  {
    id: "f12",
    subject: "d://maromba",
    tag: "#treino",
    title: "Ficha de treino ABC para quem só tem 45 minutos por dia",
    description:
      "Foco total em compostos para otimizar o tempo e a hipertrofia.",
    author: "GymRat",
    role: "Atleta",
    time: "3 d",
    votes: 420,
    comments: 78,
    imageUrl: null,
  },
  {
    id: "f13",
    subject: "d://relacionamentos",
    tag: "#ajuda",
    title: "Como lidar com amigos que só falam de trabalho no rolê?",
    description:
      "Parece que ninguém mais tem hobby além de codar e falar de framework.",
    author: "Social_Life",
    role: "User",
    time: "3 d",
    votes: 560,
    comments: 115,
    imageUrl: null,
  },
  {
    id: "f14",
    subject: "d://conspiracao",
    tag: "#alerta",
    title: "Aquele passarinho na sua janela é um drone de vigilância?",
    description:
      "Birds Aren't Real está se tornando assustadoramente plausível.",
    author: "TruthSeeker",
    role: "Teorista",
    time: "4 d",
    votes: 310,
    comments: 92,
    imageUrl: null,
  },
  {
    id: "f15",
    subject: "d://cinema",
    tag: "#news",
    title: "Christopher Nolan anuncia novo filme épico sobre buracos negros",
    description:
      "Preparem os fones de ouvido, a trilha sonora promete quebrar as janelas.",
    author: "MovieBuff",
    role: "Crítico",
    time: "5 d",
    votes: 4800,
    comments: 650,
    imageUrl: null,
  },
];
